# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BaseReactNative' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BaseReactNative

  pod 'Fabric'
  pod 'Crashlytics'
  
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

end
